version: '2'

services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/ubuntu/projecthosting/docker/nginx/certs:/etc/nginx/certs
    container_name: cont-nginx
networks: 
  default: 
    external: 
      name: net-hosting